In [21]:
import importlib

import numpy as np
import pandas as pd
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
import os

import model_functions
import utils

importlib.reload(model_functions)
importlib.reload(utils)

from model_functions import load_transition_matrix, gen_risk_matrix, gen_transition_probabilities, run_markov_cohort, \
    run_mc_sim, calculate_outcomes, plot_trace, load_costs, STAGE_ORDER, run_comparison, run_mc_sim_complex

In [3]:
STAGE_ORDER = ['F0', 'F1', 'F2', 'F3', 'F4', 'HCC', 'DC', 'LT', 'post-LT', 'Death']

MORTALITY_COLUMNS = ['Death']

DIR_HRP = "~/Documents/courses/HRP_392/"

In [22]:
cycle_len = 1/13
n_cycles = 88 * 13
cohort_size = 5 #1000  # 5
tm = load_transition_matrix('~/Documents/courses/HRP_392/final_baseline_transition_probs.csv', "_obs", cycle_length=cycle_len)
rm = gen_risk_matrix(regression_risk=1.56, progression_risk=0.6097424116233234)

initial_prevalence = [.628, 0.309, 0.035, 0.016, 0.012, 0,0,0,0,0]

# treatment starting at 12, 72 weeks of treatment
mc_trace_12_72, drug_trace_12_72 = run_mc_sim_complex(tm, initial_prevalence, n_cycles, cohort_size, starting_age=12,
                      cycle_length=cycle_len, risk_matrix=rm,
                                          begin_tx_at_cycle=0, tx_cycle_num=18, drug_stages=['F2', 'F3'])

In [ ]:
qaly_vector_discount, cost_vector_discount = calculate_outcomes(mc_trace_12_72, n_cycles, 'Semaglutide',
                                                                    risk_attenuated_cycles=risk_attenuated_cycles,
                                                                    begin_tx_at_cycle=0,
                                                                    drug_stages=drug_stages,)

In [ ]:
# treatment starting at 18, 72 weeks of treatment
mc_trace_18_72, drug_trace_18_72 = run_mc_sim_complex(tm, initial_prevalence, n_cycles, cohort_size, starting_age=12,
                      cycle_length=cycle_len, risk_matrix=rm,
                                          begin_tx_at_cycle=6*13, tx_cycle_num=18, drug_stages=['F2', 'F3'])

In [18]:
mc_trace

age_float,12.000000,12.076923,12.153846,12.230769,12.307692,12.384615,12.461538,12.538462,12.615385,12.692308,...,74.307692,74.384615,74.461538,74.538462,74.615385,74.692308,74.769231,74.846154,74.923077,75.000000
age,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,...,74.0,74.0,74.0,74.0,74.0,74.0,74.0,74.0,74.0,75.0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0
4,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0

In [19]:
drug_trace

age_float,12.000000,12.076923,12.153846,12.230769,12.307692,12.384615,12.461538,12.538462,12.615385,12.692308,...,74.307692,74.384615,74.461538,74.538462,74.615385,74.692308,74.769231,74.846154,74.923077,75.000000
age,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,...,74.0,74.0,74.0,74.0,74.0,74.0,74.0,74.0,74.0,75.0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
drug_trace.sum(axis=1)

0     0.0
1    18.0
2    18.0
3     0.0
4     0.0
dtype: float64